spring:
  application:
    name: authserver
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password: sa
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true

server:
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    use-root-path: true

jwt:
  secret: "aef154f729347b5894f64477dd62ddc2d72d1e28"
  expiration-hours: 48
  admin-expiration-hours: 1
  issuer: "AuthServer"
